name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ website ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: yarn install

    - name: Test
      run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'jancarlosanjuan'
        git config --global user.email 'jancarlosanjuan@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy